from django.db import models

# Create your models here.
class alumno(models.Model):
    clacentro = models.CharField(max_length=45,blank=True,null=True)
    nombreplan = models.CharField(max_length=45,blank=True,null=True)
    clavestado = models.CharField(max_length=45,blank=True,null=True)
    clavemuni = models.CharField(max_length=45,blank=True,null=True)
    clavelocal = models.CharField(max_length=45,blank=True,null=True)
    matricula = models.CharField(max_length=45,blank=True,null=True)
    nombres = models.CharField(max_length=45,blank=True,null=True)
    papellido = models.CharField(max_length=45,blank=True,null=True)
    sapellido = models.CharField(max_length=45,blank=True,null=True)
    curp = models.CharField(max_length=45,blank=True,null=True)
    telcasa = models.CharField(max_length=45,blank=True,null=True)
    grado = models.CharField(max_length=45,blank=True,null=True)
    grupo = models.CharField(max_length=45,blank=True,null=True)
    orden = models.CharField(max_length=45,blank=True,null=True)
   

class calificacion(models.Model):                
    clacentro = models.CharField(max_length=45,blank=True,null=True)
    claveplan = models.CharField(max_length=45,blank=True,null=True)
    nombreplan = models.CharField(max_length=45,blank=True,null=True)
    clavemate = models.CharField(max_length=45,blank=True,null=True)
    materia = models.CharField(max_length=45,blank=True,null=True)
    semestre = models.CharField(max_length=45,blank=True,null=True)
    clavegrupo = models.CharField(max_length=4,blank=True,null=True)
    turno = models.CharField(max_length=45,blank=True,null=True)
    matricula = models.CharField(max_length=45,blank=True,null=True)
    parcial_1 = models.CharField(max_length=45,blank=True,null=True)
    parcial_2 = models.CharField(max_length=45,blank=True,null=True)
    parcial_3 = models.CharField(max_length=45,blank=True,null=True)
    calificaci = models.CharField(max_length=45,blank=True,null=True)
    prompar = models.CharField(max_length=45,blank=True,null=True)
    promsem = models.CharField(max_length=45,blank=True,null=True)
    inasistenc = models.CharField(max_length=45,blank=True,null=True)
    numclases = models.CharField(max_length=45,blank=True,null=True)
    inasispar1 = models.CharField(max_length=45,blank=True,null=True)
    nclasespar = models.CharField(max_length=45,blank=True,null=True)
    inasispar2 = models.CharField(max_length=45,blank=True,null=True) 
    nclasespa2 = models.CharField(max_length=45,blank=True,null=True)
    inasispar3 = models.CharField(max_length=45,blank=True,null=True)
    nclasespa3 = models.CharField(max_length=45,blank=True,null=True)
    edoacredit = models.CharField(max_length=45,blank=True,null=True)
    grado = models.CharField(max_length=45,blank=True,null=True)
    grupo = models.CharField(max_length=45,blank=True,null=True)
    orden = models.CharField(max_length=45,blank=True,null=True)
   
