# Generated by Django 2.0.2 on 2018-11-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0002_auto_20181105_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadosalu',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo'),
        ),
    ]
