# Generated by Django 2.0.2 on 2018-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0003_auto_20181105_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadosalu',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comalu', verbose_name='Archivo'),
        ),
    ]
