# Generated by Django 2.1.3 on 2018-12-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0006_comunicadosvesp'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunicadosescolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comalu', verbose_name='Archivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Comunicados escolar',
                'verbose_name_plural': 'Comunicados escolar',
                'ordering': ['-created'],
            },
        ),
    ]
