# Generated by Django 2.1.3 on 2018-12-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0009_comunicadosescolar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunicadoescolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects', verbose_name='Imagen')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'comunicado escolar',
                'verbose_name_plural': 'comunicados escolar',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='comunicadosescolar',
        ),
    ]
