# Generated by Django 2.1.3 on 2018-12-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0010_auto_20181215_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadoescolar',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='comalu', verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='comunicadoescolar',
            name='image',
            field=models.ImageField(upload_to='comalu', verbose_name='Imagen'),
        ),
    ]
