# Generated by Django 2.1.3 on 2018-12-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0011_auto_20181215_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicadoescolar',
            name='turno',
            field=models.CharField(blank=True, choices=[('Ma', 'Matutino'), ('Ve', 'Vespertino'), ('Mi', 'Mixto')], max_length=2, null=True),
        ),
    ]
