# Generated by Django 2.1.3 on 2018-12-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0012_comunicadoescolar_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicadoescolar',
            name='turno',
        ),
        migrations.AlterField(
            model_name='comunicadoescolar',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Ma', 'Matutino'), ('Ve', 'Vespertino'), ('Mi', 'Mixto')], max_length=2, null=True),
        ),
    ]
