# Generated by Django 2.1.3 on 2018-12-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0013_auto_20181215_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadoescolar',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Di', 'Dibujo'), ('Ta', 'Taekwondo'), ('Ha', 'Hawaiano'), ('Da', 'Danza'), ('Ma', 'Marimba'), ('Vc', 'Vocalizacionycanto'), ('Ba', 'Bandadeguerra'), ('To', 'Tochito'), ('Es', 'Escolta'), ('Ba', 'Basquetbol'), ('Fu', 'Futbol'), ('Vo', 'Voleibol')], max_length=2, null=True),
        ),
    ]
