# Generated by Django 2.1.3 on 2018-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0015_remove_comunicadoescolar_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='caro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Titulo')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
            ],
        ),
    ]
