# Generated by Django 2.1.3 on 2018-12-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0016_caro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caro',
            name='image',
            field=models.ImageField(upload_to='media/projects/'),
        ),
    ]
