# Generated by Django 2.1.3 on 2018-12-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0017_auto_20181218_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caro',
        ),
    ]
