# Generated by Django 2.1.3 on 2018-12-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0019_carusel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusel',
            name='image',
            field=models.ImageField(upload_to='carousel ', verbose_name='Imagen'),
        ),
    ]
