# Generated by Django 2.1.3 on 2018-12-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0020_auto_20181220_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carusel',
            name='image',
            field=models.ImageField(upload_to='carousel', verbose_name='Imagen'),
        ),
    ]
