# Generated by Django 2.1.3 on 2019-01-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0021_auto_20181220_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=2, null=True, verbose_name='Grado')),
                ('grupo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=2, null=True, verbose_name='Grupo')),
                ('capacitacion', models.CharField(blank=True, max_length=20, verbose_name='capacitacion')),
                ('turno', models.CharField(blank=True, choices=[('Ma', 'Matutino'), ('Ve', 'Vespertino')], max_length=2, null=True)),
                ('periodolec', models.CharField(blank=True, max_length=20, verbose_name='capacitacion')),
                ('asignatura', models.CharField(blank=True, max_length=20, verbose_name='asignatura')),
                ('lunes', models.CharField(blank=True, max_length=10, verbose_name='lunes')),
                ('martes', models.CharField(blank=True, max_length=10, verbose_name='martes')),
                ('miercoles', models.CharField(blank=True, max_length=10, verbose_name='miercoles')),
                ('jueves', models.CharField(blank=True, max_length=10, verbose_name='jueves')),
                ('vierne', models.CharField(blank=True, max_length=10, verbose_name='viernes')),
                ('aula', models.CharField(blank=True, max_length=10, verbose_name='aulas')),
                ('docente', models.CharField(blank=True, max_length=40, verbose_name='docente')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comunicadosvesp',
            options={'ordering': ['-created'], 'verbose_name': 'Comunicados Docentes', 'verbose_name_plural': 'Comunicados Docentes vesp'},
        ),
    ]
