# Generated by Django 2.1.3 on 2019-01-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0022_auto_20190109_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={'verbose_name': 'horario', 'verbose_name_plural': 'horarios'},
        ),
    ]
