# Generated by Django 2.1.3 on 2019-01-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directivo', '0023_auto_20190109_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarios',
            options={},
        ),
    ]
