# Generated by Django 2.0.2 on 2018-10-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='docentes',
            new_name='docente',
        ),
    ]
