# Generated by Django 2.1.3 on 2018-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clacentro', models.CharField(blank=True, max_length=100)),
                ('nombreplan', models.CharField(blank=True, max_length=45)),
                ('claveestado', models.CharField(blank=True, max_length=45)),
                ('clavemuni', models.CharField(blank=True, max_length=50)),
                ('clavelocal', models.CharField(blank=True, max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=100)),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('papellido', models.CharField(blank=True, max_length=100)),
                ('sapellido', models.CharField(blank=True, max_length=100)),
                ('curp', models.CharField(blank=True, max_length=100)),
                ('telcasa', models.CharField(blank=True, max_length=100)),
                ('grado', models.CharField(blank=True, max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=100)),
                ('orden', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
