# Generated by Django 2.1.3 on 2018-12-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20181204_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clacentro', models.CharField(blank=True, max_length=45, null=True)),
                ('claveplan', models.CharField(blank=True, max_length=45, null=True)),
                ('clavemate', models.CharField(blank=True, max_length=45, null=True)),
                ('materia', models.CharField(blank=True, max_length=45, null=True)),
                ('semestre', models.CharField(blank=True, max_length=45, null=True)),
                ('clavegrupo', models.CharField(blank=True, max_length=4, null=True)),
                ('turno', models.CharField(blank=True, max_length=45, null=True)),
                ('parcial_1', models.CharField(blank=True, max_length=45, null=True)),
                ('parcial_2', models.CharField(blank=True, max_length=45, null=True)),
                ('parcial_3', models.CharField(blank=True, max_length=45, null=True)),
                ('calificaci', models.CharField(blank=True, max_length=45, null=True)),
                ('prompar', models.CharField(blank=True, max_length=45, null=True)),
                ('promsem', models.CharField(blank=True, max_length=45, null=True)),
                ('inasistenc', models.CharField(blank=True, max_length=45, null=True)),
                ('numclases', models.CharField(blank=True, max_length=45, null=True)),
                ('inasispar1', models.CharField(blank=True, max_length=45, null=True)),
                ('nclasespar', models.CharField(blank=True, max_length=45, null=True)),
                ('inasispar2', models.CharField(blank=True, max_length=45, null=True)),
                ('nclasespa2', models.CharField(blank=True, max_length=45, null=True)),
                ('inasispar3', models.CharField(blank=True, max_length=45, null=True)),
                ('nclasespa3', models.CharField(blank=True, max_length=45, null=True)),
                ('edoacredit', models.CharField(blank=True, max_length=45, null=True)),
                ('grado', models.CharField(blank=True, max_length=45, null=True)),
                ('grupo', models.CharField(blank=True, max_length=45, null=True)),
                ('orden', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='calificaci',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='clavegrupo',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='clavemate',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='claveplan',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='edoacredit',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='inasispar1',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='inasispar2',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='inasispar3',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='inasistenc',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='nclasespa2',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='nclasespa3',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='nclasespar',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='numclases',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='parcial_1',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='parcial_2',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='parcial_3',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='prompar',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='promsem',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='turno',
        ),
    ]
