# Generated by Django 2.1.3 on 2018-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20181204_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='nombreplan',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
