# Generated by Django 2.1.3 on 2018-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_calificacion_nombreplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='matricula',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
