# Generated by Django 2.1.3 on 2018-12-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_calificacion_matricula'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='alumno',
        ),
    ]
